### ISSUE TITLE
feature/forgotPasswordForm

### ISSUE THREAD

**Issue by tharsila** [E-A-D-S/beacademy-devstart-rubi#23]
Criar formulário para 'esqueci a senha'.
- Email

**Comment by renatadeodorio** [comment]
Criei um arquivo recovery.blade.php no users
Criei a rota no web.php
Criei a função recovery no UserController.php

**Comment by renatadeodorio** [comment]
Criei um arquivo recovery.blade.php no users
Criei a rota no web.php
Criei a função recovery no UserController.php
