### ISSUE TITLE
Reunião semanal quarta 20/07 às 19h

### ISSUE THREAD

**Issue by renatadeodorio** [E-A-D-S/beacademy-devstart-rubi#59]
-Criar features do que esta faltando no projeto;
-Delegar tarefas;

Link para reunião:
https://meet.google.com/yah-wyaw-rkx

**Comment by renatadeodorio** [comment]
feature/recuperarSenhaEmail (Eduardo /Matheus)-fazer email para squad 
feature/fixDescriçãoDoProduto (renata) -tirar tambem parte da avaliação
feature/bugFixProductMigration (matheus)

**Comment by renatadeodorio** [comment]
feature/recuperarSenhaEmail (Eduardo /Matheus)-fazer email para squad 
feature/fixDescriçãoDoProduto (renata) -tirar tambem parte da avaliação
feature/bugFixProductMigration (matheus)

**Comment by Bryan-R-Carvalho** [comment]
feature/verificarIdade (Matheus)
feature/CrudProdutos (Bryan)
